project_id = "hveizwmatqsjlbnfrsyx"

[functions.send-confirmation-email]
verify_jwt = false

[functions.verify-checkin-password]
verify_jwt = false

[functions.verify-host-password]
verify_jwt = false

[functions.host-add-guest]
verify_jwt = false
